// Generates NOTICE-THIRD-PARTY.md and a CycloneDX SBOM (sbom.cdx.json) from the lockfile via
// `pnpm licenses list --json`, and fails on licenses that are unknown or incompatible with Apache-2.0
// distribution of the desktop app. Run: node tools/license-notice.mjs [--check]
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const BLOCKED = /^(AGPL|GPL|SSPL|CC-BY-NC|BUSL|Commons-Clause|EUPL)/i;
const KNOWN_OK =
  /^(MIT|ISC|BSD-2-Clause|BSD-3-Clause|Apache-2\.0|0BSD|CC0-1\.0|Unlicense|MPL-2\.0|BlueOak-1\.0\.0|Python-2\.0|CC-BY-4\.0|CC-BY-3\.0|Zlib|W3C|Artistic-2\.0|LGPL-3\.0|LGPL-2\.1|OFL-1\.1|MIT-0|WTFPL|PSF-2\.0)/i;
const check = process.argv.includes("--check");

// Under `pnpm license:notice` the runner exposes its own entry (npm_execpath); otherwise fall back to PATH.
const pnpmArgs = ["licenses", "list", "--json", "--prod", "--filter", "@autoappz/desktop..."];
const execPath = process.env.npm_execpath;
const raw =
  execPath && /\.m?js$/.test(execPath)
    ? execFileSync(process.execPath, [execPath, ...pnpmArgs], {
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
      })
    : execFileSync("pnpm", pnpmArgs, {
        encoding: "utf8",
        shell: process.platform === "win32",
        maxBuffer: 64 * 1024 * 1024,
      });
/** @type {Record<string, {name: string, versions: string[], license: string, author?: string, homepage?: string}[]>} */
const byLicense = JSON.parse(raw);
const packages = Object.entries(byLicense).flatMap(([license, list]) => list.map((p) => ({ ...p, license })));
packages.sort((a, b) => a.name.localeCompare(b.name));

const problems = [];
for (const p of packages) {
  const expr = p.license;
  const parts = expr.split(/\s+(?:OR|AND)\s+|[()]/).filter(Boolean);
  if (
    parts.some((part) => BLOCKED.test(part.trim())) &&
    !parts.some((part) => KNOWN_OK.test(part.trim()) && /\bOR\b/.test(expr))
  ) {
    problems.push(`${p.name}: ${expr} (blocked)`);
  } else if (!parts.some((part) => KNOWN_OK.test(part.trim()))) {
    problems.push(`${p.name}: ${expr} (unknown license; review and allowlist)`);
  }
}

const notice = [
  "# Third-party notices",
  "",
  "AutoAPPZ is licensed under Apache-2.0. The desktop application bundles the following third-party packages under their own licenses. Generated by `pnpm license:notice`; do not edit by hand.",
  "",
  "| Package | Versions | License |",
  "|---|---|---|",
  ...packages.map((p) => `| ${p.name} | ${p.versions.join(", ")} | ${p.license} |`),
  "",
].join("\n");
writeFileSync("NOTICE-THIRD-PARTY.md", notice);

const sbom = {
  bomFormat: "CycloneDX",
  specVersion: "1.5",
  version: 1,
  metadata: {
    timestamp: new Date().toISOString(),
    component: {
      type: "application",
      name: "autoappz-desktop",
      version: process.env.npm_package_version ?? "0.0.0",
    },
  },
  components: packages.flatMap((p) =>
    p.versions.map((version) => ({
      type: "library",
      name: p.name,
      version,
      purl: `pkg:npm/${p.name.replace("@", "%40")}@${version}`,
      licenses: [{ expression: p.license }],
      ...(p.homepage ? { externalReferences: [{ type: "website", url: p.homepage }] } : {}),
    })),
  ),
};
writeFileSync("sbom.cdx.json", JSON.stringify(sbom, null, 2));
console.log(
  `NOTICE-THIRD-PARTY.md: ${String(packages.length)} packages; sbom.cdx.json: ${String(sbom.components.length)} components`,
);
if (problems.length > 0) {
  console.error(`License problems:\n${problems.join("\n")}`);
  if (check) process.exit(1);
}
